### ISSUE TITLE
Sending a empty body crashes app

### ISSUE THREAD

**Issue by rpkarlsson** [Visualisering/Visualisering-backend#54]
Posting without a body crashes the node process. See trace log:

``` shell
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.process (/Users/rpkn/Projects/visualisering/server/src/services/webhook-service.js:12:24)
    at IncomingMessage.<anonymous> (/Users/rpkn/Projects/visualisering/server/src/lib/http-server.js:26:30)
    at emitNone (events.js:80:13)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)
```

Just putting it here so well remember.

**Comment by Angamanga** [comment]
ok, thanks! We'll clean that up...
